---
# tasks file for postgresql
# Include per-environment variables
- name: include vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'           # CentOS-6.5
        - '{{ ansible_os_family }}-{{ ansible_distribution_version }}.yml'              # RedHat-6.5
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'     # CentOS-6
        - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'        # RedHat-6
        - '{{ ansible_distribution }}.yml'                                              # CentOS
        - '{{ ansible_os_family }}.yml'                                                 # RedHat
        - 'main.yml'
      paths: '../vars'
  tags: always

- include_tasks: preconfig.yml
  tags: config

- include_tasks: sysctl.yml
  tags: config

- include_tasks: install.yml
  tags: install

- include_tasks: "{{ ansible_os_family }}.yml"

- include_tasks: config.yml
  tags: config

- include_tasks: service.yml
  tags:
    - monitoring
    - service
    - db

- include_tasks: databases.yml
  tags: db
  when:
    - "'started' in postgresql_running.stdout"

- include_tasks: backup.yml
  tags: backup

- include_tasks: monitoring.yml
  tags: monitoring
  when:
    - postgresql_monitoring_enable == True
    - "'started' in postgresql_running.stdout"
